name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy-production:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
          with:
            url: "${{ secrets.STAGIN_KEY }}"